# Generated by Django 3.1.2 on 2021-08-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('sec_score', models.IntegerField(default=0, verbose_name='Secondary School Score')),
                ('highSec_score', models.IntegerField(default=0, verbose_name='Higher Secondary School Score')),
                ('degree_score', models.IntegerField(default=0, verbose_name='Degree Score')),
                ('etest_score', models.IntegerField(default=0, verbose_name='Electronic Test Score')),
                ('mba_score', models.IntegerField(default=0, verbose_name='MBA Score')),
            ],
        ),
    ]
