# Generated by Django 3.1.2 on 2021-08-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatusApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='Placement_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Placement Status'),
        ),
    ]
