# Generated by Django 3.1.2 on 2021-08-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatusApp', '0002_placement_placement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='Placement_status',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Placement Status'),
        ),
    ]
